### ISSUE TITLE
Support for More Than 7 Floats in a Scale

### ISSUE THREAD

**Issue by leoherzog** [RobTillaart/map2colour#9] opened 2023-04-24 16:51 UTC
Incredible library, thanks for this work!

I'd love to be able to use alternative color scales with more than 7 floats in the scale, such as Wunderground's:
```
["#111111","#21006B","#4C006B","#6B006B","#990099","#B300B3","#CC00CC","#E600E6","#FF02FF","#D100FF","#9E01FF","#6600FF","#1800FF","#144AFF","#0E74FF","#00A4FF","#00CBFF","#00E6FF","#00FFFF","#01FFB3","#7FFF00","#CEFF00","#FEFF00","#FFE601","#FFCB00","#FFAE00","#FF9900","#FE7F00","#FF4F00","#FF0700","#FF4545","#FF6968","#FF8787","#FF9E9E","#FFB5B5","#FFCFCF","#FFE8E8","#EEEEEE"]
[-60,125]
```
The NWS':
```
["#ffffff","#ffd2ff","#df8ee2","#a760c8","#5e4eac","#37c4e2","#33de9d","#7ed634","#ffff32","#fb9232","#da4f33","#b23833","#000000"]
[-10,110]
```
or windy.com's:
```
["#734669","#caacc3","#a24691","#8f59a9","#9ddbd9","#6abfb5","#64a6bd","#5d85c6","#447d63","#809318","#f3b704","#e85319","#470e00"]
[-94,-67,-40,-13,5,17,25,32,34,50,70,86,116]
```

**Comment by RobTillaart** [comment] 2023-04-24 17:01
Thanks for the compliment,

What is the max number of colors you want?
I'll have a look.

**Comment by leoherzog** [comment] 2023-04-24 17:21
Well, the optimist in me would say as many as RAM allows, but perhaps up to 16?

**Comment by RobTillaart** [comment] 2023-04-24 17:37
Created a develop branch that has dynamic allocation of the internal RGB array. 
One test example, that seems to work.
build is running.

(will become a 0.2.0 version)

The derived class is not dynamic yet.

**Comment by RobTillaart** [comment] 2023-04-24 17:39
> Well, the optimist in me would say as many as RAM allows, but perhaps up to 16?

Dynamic allocation allows quite a lot, but I recall that some boards have a limit of allocating 256 bytes max.
So 256 bytes per RGB is quite a bit (for an Arduino UNO), especially knowing it interpolates in between.

So the optimist in you might be happy 😎

**Comment by RobTillaart** [comment] 2023-04-24 18:25
@leoherzog
Code seems to be 95% OK now, 

The build fails but I understand the problem (default colors are gone) but you can give it a try.

**Comment by RobTillaart** [comment] 2023-04-24 19:02
@leoherzog 
windys demo
```cpp
//
//    FILE: map2colour_windys_demo.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: demo
//     URL: https://github.com/RobTillaart/map2colour

#include "Arduino.h"
#include "map2colour.h"

map2colour mc(13);

float windys_values[13] = { -94,-67,-40,-13,5,17,25,32,34,50,70,86,116};
uint32_t windys_colour[13] =
{
  0x734669, 0xcaacc3, 0xa24691, 0x8f59a9, 0x9ddbd9, 0x6abfb5, 0x64a6bd, 
  0x5d85c6, 0x447d63, 0x809318, 0xf3b704, 0xe85319, 0x470e00
};


void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);
  Serial.print("MAP2COLOUR_LIB_VERSION: ");
  Serial.println(MAP2COLOUR_LIB_VERSION);
  Serial.println();

  //  load the windys arrays
  mc.begin(windys_values, windys_colour);

  //  show the interpolating
  for (float i = -100; i < 125; i += 5)
  {
    uint32_t rgb = mc.map2RGB(i);
    Serial.print(i);
    Serial.print("\t");
    Serial.println(rgb, HEX);
  }
  Serial.println();
}

void loop()
{
}

// -- END OF FILE --
```

output
```
Arduino\libraries\map2colour\examples\map2colour_windys_demo\map2colour_windys_demo.ino
MAP2COLOUR_LIB_VERSION: 0.2.0

-100.00	734669
-95.00	734669
-90.00	7F5576
-85.00	906887
-80.00	A07A97
-75.00	B08DA8
-70.00	C0A0B9
-65.00	C7A4BF
-60.00	BF91B6
-55.00	B87EAC
-50.00	B06BA3
-45.00	A9589A
-40.00	A24691
-35.00	9E4995
-30.00	9A4D99
-25.00	97509E
-20.00	9354A2
-15.00	9057A7
-10.00	916EB1
-5.00	9592BE
0.00	99B6CB
5.00	9DDBD9
10.00	87CFCA
15.00	72C3BB
20.00	67B5B8
25.00	64A6BD
30.00	5F8EC3
35.00	477E5E
40.00	5A8546
45.00	6D8C2F
50.00	809318
55.00	9C9C13
60.00	B9A50E
65.00	D6AE09
70.00	F3B704
75.00	EF970A
80.00	EC7811
85.00	E85917
90.00	D24915
95.00	B73E11
100.00	9C320D
105.00	822709
110.00	671B05
115.00	4C1000
120.00	470E00
```

**Comment by RobTillaart** [comment] 2023-04-24 19:11
> The build fails but I understand the problem (default colors are gone) but you can give it a try.

build is OK again, all examples compile => happy

Need to update the readme file to reflect the changes in 0.2.0.
tomorrow

**Comment by leoherzog** [comment] 2023-04-24 20:16
Holy cow. This was all coded and done literal hours after I put in the issue! I didn't expect you to turn this around so quickly. Bravo! Thank you very much!

**Comment by RobTillaart** [comment] 2023-04-24 20:24
It was an issue I had been thinking over before, so I had design ideas somewhere in a obscure corner of the mind.
If you have time, please try to verify if it works for you,

Now it is time  (~10:30 PM here) to cool down

**Comment by RobTillaart** [comment] 2023-04-25 17:38
@leoherzog 
Did a few minor edits today, so you might need to download the develop branch again.

**Comment by leoherzog** [comment] 2023-04-25 19:14
Okay. I've removed my 0.1.6 installed library, installed the latest `develop` branch, and made the following:

```C
uint32_t tempColors[] = {
  0x00734669, // #734669
  0x00caacc3, // #caacc3
  0x00a24691, // #a24691
  0x008f59a9, // #8f59a9
  0x009ddbd9, // #9ddbd9
  0x006abfb5, // #6abfb5
  0x0064a6bd, // #64a6bd
  0x005d85c6, // #5d85c6
  0x00447d63, // #447d63
  0x00809318, // #809318
  0x00f3b704, // #f3b704
  0x00e85319, // #e85319
  0x00470e00  // #470e00
}; // windy.com scale
float tempDomain[] = {-70, -55, -40, -25, -15, -8.33, -3.89, 0, 1, 10, 21, 30, 45};
map2colour m2c;

void setup() {
  // ...
  m2c.begin(tempDomain, tempColors);
}

void loop() {
  // ...
  uint32_t rgbColor = m2c.map2RGB(temp); 
  byte r = (rgbColor >> 16) & 0xFF;
  byte g = (rgbColor >> 8) & 0xFF;
  byte b = rgbColor & 0xFF;

  Serial.print("Setting to #");
  Serial.print(r, HEX);
  Serial.print(g, HEX);
  Serial.print(b, HEX);
  Serial.println();
}
```
and every temp that I pull down (between 1°C and 7°C right now) is giving back exactly `#64A6BD`. It's as if it's stuck on giving the nearest one exactly (that's the 7th element in the array) instead of doing interpolation or something?

**Comment by RobTillaart** [comment] 2023-04-25 19:17
Will try to recreate the problem here (thx for the code)

**Comment by RobTillaart** [comment] 2023-04-25 19:23
Slightly modified your code. 
The problem is not setting the size in the constructor.
Give it a try.

```cpp
//    FILE: .ino
//  AUTHOR: Rob Tillaart
// PURPOSE:
//     URL:


#include "Arduino.h"
#include "map2colour.h"


uint32_t tempColors[] = {
  0x00734669, // #734669
  0x00caacc3, // #caacc3
  0x00a24691, // #a24691
  0x008f59a9, // #8f59a9
  0x009ddbd9, // #9ddbd9
  0x006abfb5, // #6abfb5
  0x0064a6bd, // #64a6bd
  0x005d85c6, // #5d85c6
  0x00447d63, // #447d63
  0x00809318, // #809318
  0x00f3b704, // #f3b704
  0x00e85319, // #e85319
  0x00470e00  // #470e00
}; // windy.com scale
float tempDomain[] = { -70, -55, -40, -25, -15, -8.33, -3.89, 0, 1, 10, 21, 30, 45};

map2colour m2c(13);  // <<<<<<<<<<<<

void setup() {
  Serial.begin(115200);
  Serial.println(__FILE__);

  m2c.begin(tempDomain, tempColors);

  for (int i = -70; i < 50; i++)
  {
    uint32_t rgbColor = m2c.map2RGB(i);
    byte r = (rgbColor >> 16) & 0xFF;
    byte g = (rgbColor >> 8) & 0xFF;
    byte b = rgbColor & 0xFF;

    Serial.print(i);
    Serial.print("\t Setting to #");
    Serial.print(r, HEX);
    Serial.print(g, HEX);
    Serial.print(b, HEX);
    Serial.println();
  }


}

void loop() {

}

// -- END OF FILE --
```

**Comment by RobTillaart** [comment] 2023-04-25 19:25
One more fix

```cpp
    Serial.print(i);
    Serial.print("\t Setting to #");
    if (r < 16) Serial.print("0");   //  <<<<<<<<<<<<<
    Serial.print(r, HEX);
    if (g < 16) Serial.print("0");   //  <<<<<<<<<<<<<
    Serial.print(g, HEX);
    if (b < 16) Serial.print("0");   //  <<<<<<<<<<<<<
    Serial.print(b, HEX);
    Serial.println();
```

**Comment by leoherzog** [comment] 2023-04-25 19:26
![Woman sitting in chair making an "oh duh, I should have known that" face](https://media.tenor.com/8icGarHeQ3gAAAAC/obviously.gif)

Working perfectly, thanks 😳

**Comment by RobTillaart** [comment] 2023-04-25 19:27
Think that your first run only used the first 7 values as the default size is 7.

**Comment by leoherzog** [comment] 2023-04-25 19:27
That makes sense! It was on the ~~lower~~ upper bounds with every number. Of course!

**Comment by RobTillaart** [comment] 2023-04-25 19:29
With size 7 it indeed stops at the 7th colour.
```
-8	 Setting to #69BDB5
-7	 Setting to #68B7B7
-6	 Setting to #66B1B9
-5	 Setting to #65ACBB
-4	 Setting to #64A6BC
-3	 Setting to #64A6BD
-2	 Setting to #64A6BD
-1	 Setting to #64A6BD
0	 Setting to #64A6BD
1	 Setting to #64A6BD
2	 Setting to #64A6BD
3	 Setting to #64A6BD
4	 Setting to #64A6BD
```

**Comment by RobTillaart** [comment] 2023-04-25 19:32
Are these temperatures in Fahrenheit? 
float tempDomain[] = { -70, -55, -40, -25, -15, -8.33, -3.89, 0, 1, 10, 21, 30, 45};

**Comment by leoherzog** [comment] 2023-04-25 19:34
Weirdly, no.

![windy.com screenshot showcasing the temperature scales](https://user-images.githubusercontent.com/5376265/234383779-f61cb264-5eca-4302-ae66-318f8ca9696e.png)

**Comment by leoherzog** [comment] 2023-04-25 19:35
But I really like its sharp division between above and below freezing. It highlights boundaries interestingly. The colors themselves are more muted and pastel than some other scales as well. I really like it.

**Comment by RobTillaart** [comment] 2023-04-25 19:37
Found it 
// float tempDomain[] = { -70, -55, -40, -25, -15, -8.33, -3.89, 0, 1, 10, 21, 30, 45};  // Celsius
// float windys_values[13] = { -94,-67,-40,-13,5,17,25,32,34,50,70,86,116};  //  Fahrenheit.

**Comment by RobTillaart** [comment] 2023-04-25 19:40
If you really want a sharp division around 0 in your program try the following  => double zero

```cpp
float tempDomain[] = { -70, -55, -40, -25, -15, -8.33, -3.89, 0, 0, 1, 10, 21, 30, 45}; // Celsius

uint32_t tempColors[] = {
  0x00734669, // #734669
  0x00caacc3, // #caacc3
  0x00a24691, // #a24691
  0x008f59a9, // #8f59a9
  0x009ddbd9, // #9ddbd9
  0x006abfb5, // #6abfb5
  0x0064a6bd, // #64a6bd
  0x00640000,  // <<<<<<<<<<<  extra zero for sharp edge
  0x005d85c6, // #5d85c6
  0x00447d63, // #447d63
  0x00809318, // #809318
  0x00f3b704, // #f3b704
  0x00e85319, // #e85319
  0x00470e00  // #470e00
};
```

you must set size to 14 of course with the double zero.

**Comment by RobTillaart** [comment] 2023-04-25 19:55
Windy.com makes the sharp edge by having both 32F and 34F in their table, gives a steep gradient.

**Comment by leoherzog** [comment] 2023-04-25 20:21
Yeah, they have 32°F and 34°F values that I have with my matching 0°C and 1°C values. I simply took their default scale and converted it to Celsius.

**Comment by RobTillaart** [comment] 2023-04-26 07:01
Time to merge the branch.

**Comment by RobTillaart** [comment] 2023-04-26 07:27
Merged and released the 0.2.0 version. As all seem to be working I close the issue.
Feel free to reopen it (or just add comments) if needed.

Thanks!

**Closed as completed by RobTillaart** 2023-04-26 07:27 UTC
Labels: enhancement, question

**Comment by leoherzog** [comment] 2023-04-26 12:56
Thank YOU!

**Comment by RobTillaart** [comment] 2023-04-26 13:25
Maybe you can post some photos in the future?

**Comment by leoherzog** [comment] 2023-04-26 13:56
Photos of the project I'm working on?

Before, I was using Google Apps Script, then Cloudflare Workers, to parse and cache temperatures from across the state that I live in. I then fetched the cached colors and set them on the Arduino. Because of your library, I've now been able to move all of the temperature fetching and parsing logic to directly on the Arduino with no middle-man!

![PXL_20230423_165924560](https://user-images.githubusercontent.com/5376265/234598232-1bf75521-2d6e-4140-8f12-086012646ca4.jpg)
![PXL_20230421_001548358 MP](https://user-images.githubusercontent.com/5376265/234598239-abde4a86-a658-4d5a-b0b3-5ca77cf39219.jpg)

**Comment by RobTillaart** [comment] 2023-04-26 14:10
Looks superb, I recognize Michigan!

**Comment by RobTillaart** [comment] 2026-01-28 08:11
@leoherzog 

Just wondering how your project looks now in the severe cold?
Is it out of scale?

**Comment by leoherzog** [comment] 2026-01-29 03:09
@RobTillaart Very sweet of you to remember and to ask! Yes, we had temperatures reach -4°F/-20°C here. Some areas in the Upper Pinensula reached -36°F/-37°C last week. I use and look at this wall art project every day.

![Photo of a wooden map of the state of Michigan with light blue and light purple lights dotted across it](https://github.com/user-attachments/assets/7e78c782-2aec-4453-b1f0-a30a49e19ae6)

The LEDs fade from 0% to 100% brightness between local sunrise and solar noon, then back from 100% to 0% from solar noon to sunset. Thanks very much to you and to this library for making it possible.

**Comment by leoherzog** [comment] 2026-01-29 03:12
I use a saturated windy.com temperature scale that has a domain from -70°C to 45°C :)

https://github.com/leoherzog/michigan-temp-map

**Comment by RobTillaart** [comment] 2026-01-29 08:10
@leoherzog 
Thanks for the donation!
